/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoleksiIndexRouteImport } from './routes/koleksi.index'
import { Route as KoleksiBookIdRouteImport } from './routes/koleksi.$bookId'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoleksiIndexRoute = KoleksiIndexRouteImport.update({
  id: '/koleksi/',
  path: '/koleksi/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoleksiBookIdRoute = KoleksiBookIdRouteImport.update({
  id: '/koleksi/$bookId',
  path: '/koleksi/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/koleksi/$bookId': typeof KoleksiBookIdRoute
  '/koleksi/': typeof KoleksiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/koleksi/$bookId': typeof KoleksiBookIdRoute
  '/koleksi': typeof KoleksiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/galeri': typeof GaleriRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/koleksi/$bookId': typeof KoleksiBookIdRoute
  '/koleksi/': typeof KoleksiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/galeri'
    | '/kontak'
    | '/program'
    | '/tentang'
    | '/koleksi/$bookId'
    | '/koleksi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/galeri'
    | '/kontak'
    | '/program'
    | '/tentang'
    | '/koleksi/$bookId'
    | '/koleksi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/galeri'
    | '/kontak'
    | '/program'
    | '/tentang'
    | '/koleksi/$bookId'
    | '/koleksi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GaleriRoute: typeof GaleriRoute
  KontakRoute: typeof KontakRoute
  ProgramRoute: typeof ProgramRoute
  TentangRoute: typeof TentangRoute
  KoleksiBookIdRoute: typeof KoleksiBookIdRoute
  KoleksiIndexRoute: typeof KoleksiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koleksi/': {
      id: '/koleksi/'
      path: '/koleksi'
      fullPath: '/koleksi/'
      preLoaderRoute: typeof KoleksiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koleksi/$bookId': {
      id: '/koleksi/$bookId'
      path: '/koleksi/$bookId'
      fullPath: '/koleksi/$bookId'
      preLoaderRoute: typeof KoleksiBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GaleriRoute: GaleriRoute,
  KontakRoute: KontakRoute,
  ProgramRoute: ProgramRoute,
  TentangRoute: TentangRoute,
  KoleksiBookIdRoute: KoleksiBookIdRoute,
  KoleksiIndexRoute: KoleksiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
